events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    client_max_body_size 100M;

    server {
        listen 80;
        server_name _;

        location / {
            # Proxy to the Uvicorn server running in the same container
            proxy_pass http://fastapi-service:8000;

            proxy_http_version 1.1;
            # proxy_set_header Connection ""; # Keep connection open
            proxy_set_header Connection "keep-alive";

            # Absolute zero buffering
            proxy_buffering off;  # DISBALE Nginx buffering
            proxy_request_buffering off;
            proxy_cache off;   # Ensure no caching of the video
            tcp_nodelay on;
            tcp_nopush off;

            # Pass original headers for FastAPI's identification
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            chunked_transfer_encoding on;

            # Increase timeouts for long-running video streams
            proxy_read_timeout 3600s;        # Keep stream open for up to 1 hour
            proxy_send_timeout 3600s;
        }
    }
}