
services:
    finetune-service:
        # image: lcc_finetune:latest
        build: ./
        container_name: finetune_model
        privileged: true
        network_mode: "host"
        ipc: "host"
        shm_size: '2gb'  # Give it plenty of space for video frames
        environment:
            YOLO_CONFIG_DIR: "/tmp"
            DBHOST: "vdms-service"
            UDF_HOST: "udf-service"
            MODEL_NAME: "yolo11n"
            CUSTOM_MODEL_FLAG: "False"
            RESIZE_FLAG: "True"
            OMIT_DETECTIONS_FLAG: "False"
            CPU_BATCH_SIZE: 1
            GPU_BATCH_SIZE: 1
            DEBUG: "1"
            DEVICE: "GPU"
            INGESTION: "object,face"
            WATCH_DIR: "/watch_dir"
            http_proxy: "${http_proxy}"
            HTTP_PROXY: "${HTTP_PROXY}"
            https_proxy: "${https_proxy}"
            HTTPS_PROXY: "${HTTPS_PROXY}"
            no_proxy: "video-service,localhost,127.0.0.1,vdms-service,udf-service,${no_proxy}"
            NO_PROXY: "video-service,localhost,127.0.0.1,vdms-service,udf-service,${NO_PROXY}"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ../../inputs:/watch_dir:ro
            - ./app:/home
            - ${LOCAL_DATA_DIR}:/dataset
        networks:
            - appnet
        restart: always
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          count: all


# secrets:
#     self_key:
#         file: ../certificate/self.key
#     self_crt:
#         file: ../certificate/self.crt


# networks:
#     appnet:
#         driver: overlay
#         attachable: true


# volumes:
#     app-content:
#     vdms-content:
