# GENERAL
CODE_DIR_DEFAULT = "/home"
CUSTOM_MODEL_FLAG_DEFAULT = False
DEBUG_DEFAULT = "0"
DEVICE_DEFAULT = "CPU"
MAX_WORKERS = 4  # 4  # 6
OMIT_DETECTIONS_FLAG_DEFAULT = False
SHARED_OUTPUT_DEFAULT = "/var/www/mp4"
TEST_MODE_DEFAULT = False
TMP_LOCATION_DEFAULT = "/var/www/cache"
SMART_FILTERING_ENABLED = True

# VIDEO WRITER
CLIP_DURATION_DEFAULT = 10
TARGET_FPS = 15.0

# VDMS
DBHOST_DEFAULT = "vdms-service"
DBPORT_DEFAULT = 55555
ENABLE_QUERYING_DEFAULT = False  # False, True
INGESTION_DEFAULT = "object"  # object,face
UDF_HOST_DEFAULT = "udf-service"
UDF_PORT_DEFAULT = 5011

# MODEL
DETECTION_THRESHOLD_DEFAULT = 0.1  # 0.25
IOU_THRESHOLD_DEFAULT = 0.1  #  0.7
DYNAMIC_FLAG_DEFAULT = True
HALF_FLAG_DEFAULT = True
MAX_DETECTIONS = 100
MODEL_H = 640
MODEL_W = 640
MODEL_MAX_BATCH_SIZE = 64
MODEL_NAME_DEFAULT = "yolo11n"
MODEL_PRECISION = "FP16"

# SMART FILTERING (RESIZE, BKGD SUB, THRESHOLD, DILATE)
# Enable if resolution > 2K 1920x1080
SMART_FILTERING_PIXEL_CONSTRAINT = 1920 * 1080
SMART_FILTERING_WARMUP = False  # True, False
BKGD_SUB_INCLUDE_HISTORY = False  # True, False
BKGD_SUB_INCLUDE_HISTORY_DILATE_KERNEL_SIZE = 15  # 21  #15
BKGD_SUB_INCLUDE_HISTORY_METHOD = "or"  # "and", or
BKGD_SUB_INCLUDE_HISTORY_TEMPORAL_SIZE = 3
BKGD_SUB_MOG2_DETECTSHADOWS = False
BKGD_SUB_MOG2_HISTORY = int(2 * TARGET_FPS)
BKGD_SUB_MOG2_LR = 1 / BKGD_SUB_MOG2_HISTORY  # 0.002  # 1 / BKGD_SUB_MOG2_HISTORY
BKGD_SUB_MOG2_VARTHRESHOLD = 50  # 30  # 20  #10
DILATE_KERNEL_SIZE = 5  # (3, 3)
RESIZE_FLAG_DEFAULT = False
ROI_BB_FULL_RES_PADDING = int(0.02 * MODEL_W)  # 10, ~13
ROI_CONTAINMENT_THRESH = 0.95
ROI_DISTANCE_THRESH_RATIO = 0.05  # 0.10  #.15  # 0.05
ROI_MAX_RELATIVE_SIZE_RATIO = 1  # 1  # 0.8
ROI_MERGE_SIZE_LIMIT = MODEL_W * 1.25
ROI_MIN_AREA_RATIO = 0.01
ROI_RETURN_BYTES = True
THRESHOLD_MAX_VALUE = 255
THRESHOLD_VALUE = 127

# VISUALIZATION
# Bounding boxes returned from pipeline
# object (includes yolo), motion (includes bbs no yolo)
DETECTION_TYPE_DEFAULT = "object"  # object, motion
DISPLAY_FRAME_QUALITY = 60
DISPLAY_FRAME_SIZE = (640, 360)  # (640, 360), (960, 540)
THICKNESS = 2
