
FROM openvisualcloud/xeon-ubuntu2204-media-nginx:23.1@sha256:d19eb597dc210134063803630ae2ea1ec84dfd4189138f59551e2f5ed047284a as build

ENV VIRTUAL_ENV=/opt/venv
ARG DEBIAN_FRONTEND=noninteractive

# fixes CVE-2023-4911 vulnerability on Ubuntu 22.04
RUN apt-get update
RUN apt-get install --only-upgrade libc-bin libc6  && \
    apt-get install -y -q  --no-install-recommends python3-setuptools \
    python3-tornado python3-ply python3-pip python3-venv \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY resources /home/resources
COPY requirements.* /home/

ARG DEVICE="CPU"
ENV DEVICE="${DEVICE}"

RUN if [ "${DEVICE}" = "CPU" ]; then \
        pip3 install --no-cache-dir "torch==2.9.1" "torchvision==0.24.1" --index-url https://download.pytorch.org/whl/cpu; \
    else \
        pip3 install --no-cache-dir "torch==2.9.1" "torchvision==0.24.1" ; \
    fi;
# RUN pip3 install --no-cache-dir --require-hashes -r /home/requirements.txt && \
#     pip3 install --no-cache-dir --require-hashes -r /home/requirements.${DEVICE}.txt
RUN pip3 install --no-cache-dir -r /home/requirements.in && \
    pip3 install --no-cache-dir -r /home/requirements.${DEVICE}.txt

# RUN pip3 install --no-cache-dir openvino-dev>=2024.6.0
RUN omz_downloader --list /home/resources/models/models.lst -o /home/resources/models --precisions FP16
