
worker_processes auto;
worker_rlimit_nofile 8192;
daemon off;

events {
    worker_connections  4096;
}

http {

    # Include MIME types
    include mime.types;
    default_type application/octet-stream;

    # Basic logging
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    # `proxy_read_timeout` maximum time Nginx will wait for a response from a proxied server.
    #   If the proxied server does not send any data within this time, Nginx will close the connection.
    #   Default: 60
    proxy_read_timeout 300s;

    # `proxy_send_timeout`: maximum time allowed for Nginx to transmit a request to a proxied server.
    #   If the proxied server does not receive data within this timeframe during a write operation, Nginx will close the connection.
    #   Default: 60
    proxy_send_timeout 300s;

    # `proxy_connect_timeout`: maximum time NGINX will wait while establishing a connection with an upstream (proxied) server.
    #   Default: 60
    # proxy_connect_timeout 300s;

    # include mime.types;
    # default_type application/octet-stream;

    server {
        listen 8080;
        server_name _;
        # client_body_timeout 10s;
        # client_header_timeout 10s;
        # client_max_body_size 1024M;
        client_max_body_size 2G; # 8K frames are huge
        sendfile on;

        location /api/ {
            add_header Cache-Control no-cache;
            proxy_pass http://localhost:2222;
        }

        location /mp4 {
            root /var/www;
        }

        location /gen {
            internal;
            root /var/www;
        }

        # location / {
        #     # proxy_http_version 1.1;

        #     # Mandatory for WebSocket support
        #     proxy_set_header Upgrade $http_upgrade;
        #     proxy_set_header Connection "upgrade";

        #     # Standard proxy headers
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        #     proxy_read_timeout 86400;
        # }
    }
}

